#!/bin/sh
# Client profile export for Apple, Windows and Android devices. Sourced by
# ikev2-manager, whose configuration helpers and globals it uses.

xml_escape() {
	printf '%s' "$1" | awk '{
		for (i = 1; i <= length($0); i++) {
			character = substr($0, i, 1)
			if (character == "&")
				printf "&amp;"
			else if (character == "<")
				printf "&lt;"
			else if (character == ">")
				printf "&gt;"
			else if (character == "\"")
				printf "&quot;"
			else if (character == sprintf("%c", 39))
				printf "&apos;"
			else
				printf "%s", character
		}
	}'
}

profile_uuid() {
	value="$(printf '%s' "$1" | sha256sum | awk '{ print toupper(substr($1, 1, 32)) }')"
	printf '%s-%s-%s-%s-%s\n' "${value%????????????????????????}" \
		"$(printf '%s' "$value" | cut -c9-12)" \
		"$(printf '%s' "$value" | cut -c13-16)" \
		"$(printf '%s' "$value" | cut -c17-20)" \
		"$(printf '%s' "$value" | cut -c21-32)"
}

profile_secret() {
	awk -F '\t' -v user="$1" '$1 == user { print $2; found=1; exit } END { exit found ? 0 : 1 }' \
		"$users_db"
}

profile_password() {
	local secret
	secret="$(profile_secret "$1")" || return 1
	case "$secret" in
		0s*) printf '%s' "${secret#0s}" | openssl base64 -d -A ;;
		\"*\")
			secret="${secret#\"}"
			printf '%s' "${secret%\"}"
			;;
		*) printf '%s' "$secret" ;;
	esac
}

export_apple_profile() {
	local user="$1" escaped_user identity raw_password password payload_uuid profile_uuid_value name mtu
	identity="$(xml_escape "$(getv server identity)")"
	raw_password="$(profile_password "$user")" || die 'VPN user password cannot be decoded'
	password="$(xml_escape "$raw_password")"
	escaped_user="$(xml_escape "$user")"
	mtu="$(getv_default server mtu 1400)"
	name="$(xml_escape "IKEv2 - $user")"
	payload_uuid="$(profile_uuid "apple-payload:$identity:$user")"
	profile_uuid_value="$(profile_uuid "apple-profile:$identity:$user")"
	cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
<key>PayloadContent</key><array><dict>
<key>PayloadType</key><string>com.apple.vpn.managed</string>
<key>PayloadVersion</key><integer>1</integer>
<key>PayloadIdentifier</key><string>ru.nikitid.ikev2.$payload_uuid</string>
<key>PayloadUUID</key><string>$payload_uuid</string>
<key>PayloadDisplayName</key><string>$name</string>
<key>UserDefinedName</key><string>$name</string>
<key>VPNType</key><string>IKEv2</string>
<key>IKEv2</key><dict>
<key>RemoteAddress</key><string>$identity</string>
<key>RemoteIdentifier</key><string>$identity</string>
<key>LocalIdentifier</key><string>$escaped_user</string>
<key>AuthenticationMethod</key><string>None</string>
<key>ExtendedAuthEnabled</key><integer>1</integer>
<key>AuthName</key><string>$escaped_user</string>
<key>AuthPassword</key><string>$password</string>
<key>DeadPeerDetectionRate</key><string>Medium</string>
<key>DisableMOBIKE</key><integer>0</integer>
<key>DisableRedirect</key><integer>0</integer>
<key>EnablePFS</key><integer>1</integer>
<key>MTU</key><integer>$mtu</integer>
</dict>
</dict></array>
<key>PayloadType</key><string>Configuration</string>
<key>PayloadVersion</key><integer>1</integer>
<key>PayloadIdentifier</key><string>ru.nikitid.ikev2.profile.$profile_uuid_value</string>
<key>PayloadUUID</key><string>$profile_uuid_value</string>
<key>PayloadDisplayName</key><string>$name</string>
<key>PayloadDescription</key><string>IKEv2 VPN profile generated by IKEv2 Manager.</string>
</dict></plist>
EOF
}

export_windows_profile() {
	local user="$1" identity dns name routing
	identity="$(xml_escape "$(getv server identity)")"
	dns="$(xml_escape "$(getv server dns4)")"
	name="$identity"
	case " $(normalize_list "$(getv_default server local_ts 0.0.0.0/0)") " in
		*' 0.0.0.0/0 '*) routing='ForceTunnel' ;;
		*) routing='SplitTunnel' ;;
	esac
	cat <<EOF
<VPNProfile><ProfileName>$name</ProfileName><RememberCredentials>true</RememberCredentials><AlwaysOn>false</AlwaysOn><DomainNameInformation><DomainName>.</DomainName><DnsServers>$dns</DnsServers><AutoTrigger>false</AutoTrigger><Persistent>false</Persistent></DomainNameInformation><NativeProfile><Servers>$identity</Servers><RoutingPolicyType>$routing</RoutingPolicyType><NativeProtocolType>IKEv2</NativeProtocolType><CryptographySuite><AuthenticationTransformConstants>GCMAES256</AuthenticationTransformConstants><CipherTransformConstants>GCMAES256</CipherTransformConstants><PfsGroup>ECP384</PfsGroup><DHGroup>ECP384</DHGroup><IntegrityCheckMethod>SHA384</IntegrityCheckMethod><EncryptionMethod>AES_GCM_256</EncryptionMethod></CryptographySuite><Authentication><UserMethod>Eap</UserMethod><Eap><Configuration><EapHostConfig xmlns="http://www.microsoft.com/provisioning/EapHostConfig"><EapMethod><Type xmlns="http://www.microsoft.com/provisioning/EapCommon">26</Type><VendorId xmlns="http://www.microsoft.com/provisioning/EapCommon">0</VendorId><VendorType xmlns="http://www.microsoft.com/provisioning/EapCommon">0</VendorType><AuthorId xmlns="http://www.microsoft.com/provisioning/EapCommon">0</AuthorId></EapMethod><Config xmlns="http://www.microsoft.com/provisioning/EapHostConfig"><Eap xmlns="http://www.microsoft.com/provisioning/BaseEapConnectionPropertiesV1"><Type>26</Type><EapType xmlns="http://www.microsoft.com/provisioning/MsChapV2ConnectionPropertiesV1"><UseWinLogonCredentials>false</UseWinLogonCredentials></EapType></Eap></Config></EapHostConfig></Configuration></Eap></Authentication></NativeProfile></VPNProfile>
EOF
}

export_android_profile() {
	local user="$1" password
	password="$(profile_password "$user")" || die 'VPN user does not exist'
	cat <<EOF
Profile: IKEv2 - $user
Type: IKEv2 EAP (username/password)
Server: $(getv server identity)
Remote ID: $(getv server identity)
Username: $user
Password: $password
CA certificate: Use system certificates / automatic validation
DNS supplied by VPN: $(getv server dns4)
EOF
}

export_user_profile() {
	local platform="${1:-}" user="${2:-}"
	valid_user "$user" || die 'Invalid username'
	user_exists "$user" || die 'VPN user does not exist'
	[ "$(getv server enabled)" = 1 ] || die 'Inbound server is disabled'
	case "$platform" in
		apple) export_apple_profile "$user" ;;
		windows) export_windows_profile "$user" ;;
		android) export_android_profile "$user" ;;
		*) die 'Expected profile platform: apple, windows or android' ;;
	esac
}
